### PR TITLE
Test using Jest too

### PR DESCRIPTION
**Pull request by vadimdemedes**
Checking if Ink and `ink-testing-library` runs fine in Jest.

### CODE REVIEW

**Comment by thephilwells** [comment]
Sorry, I'm a little in the weeds still. I have these in my project's `package.json`:

**Comment by thephilwells** [comment]
Sorry, I'm a little in the weeds still. I have these in my project's `package.json`:
```json
{
    "@babel/runtime": "^7.10.3",
    "chalk": "^4.1.0",
    "ink": "^3.0.0-6",
    "react": "^16.8.4"
  },
  "devDependencies": {
    "@babel/cli": "^7.10.3",
    "@babel/core": "^7.10.3",
    "@babel/plugin-transform-runtime": "^7.10.3",
    "@babel/preset-env": "^7.10.3",
    "@babel/preset-react": "^7.10.1",
    "babel-jest": "^26.1.0",
    "babel-polyfill": "^6.26.0",
    "ink-testing-library": "^2.0.0",
    "jest": "^26.1.0"
  },
  "jest": {
    "testMatch": [
      "**/*.test.js"
    ]
  }
```

And here's my `.babelrc`:
```json
{
  "presets": ["@babel/env", "@babel/react"],
  "plugins": ["@babel/transform-runtime"]
}
```

But I'm still getting the error described [here](https://github.com/vadimdemedes/ink/issues/311#issuecomment-656161324)

Am I misconfiguring something? Apologies for making you do tech support. I'm sure it's some simple user error on my part.

**Comment by thephilwells** [comment]
I'm able to work around this in my project by adding a flag when I run `render`:
```javascript
render(<App />, {patchConsole: false})
```

So I'm able to proceed. Still not sure what was causing that constructor to go missing..

**Comment by vadimdemedes** [comment]
No worries, I published `2.0.1` of this library which includes that change, so you can skip that hack.

**Pull request closed without merging**
